# action.yml
name: 'hello world'
description: 'say g''day and record the time'
inputs:
  who-to-greet:
    description: 'the welcome individual'
    required: true
    default: 'mate'
outputs:
  time:
    description: 'when it went down'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
